#!/bin/sh

#   Extended syntax for fslswapdim
#
#   Mark Jenkinson
#   FMRIB Image Analysis Group
#
#   Copyright (C) 2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.


get_axis(){
    # search for either $1 or its reverse in $2 $3 $4
    # e.g. get_axis RL AP SI LR would return -z (as $1 = $4 but backwards)
    # whereas get_axis RL AP SI RL would return z (as $1 = $4)
    ax="";
    pre="";
    k2=`echo $1 | tr RLAPSI LRPAIS`;
    for fn in "$2:x" "$3:y" "$4:z" ; do
	ff=`echo $fn | sed 's/:.*//'`;
	aa=`echo $fn | sed 's/.*://'`;
	if [ $ff = $1 ] ; then ax=$aa ; fi
	if [ $ff = $k2 ] ; then ax=$aa ; pre="-" ; fi
    done
    ax="${pre}${ax}";
    echo $ax;
}


if [ $# -lt 4 ] ; then
  echo "Usage: fslswapdim2 <input> <a> <b> <c> [output]

  where a,b,c represent the new x,y,z axes in terms of the
  old axes.  They can take values of -x,x,y,-y,z,-z
  or RL,LR,AP,PA,SI,IS (in the case of nifti inputs)
  e.g.  fslswapdim2 invol y x -z outvol
  or    fslswapdim2 invol RL PA IS outvol
  where the latter will convert to axial slicing 
  (to match the avg152 images)"
  exit 1;
fi

filetype=`$FSLDIR/bin/fslval $1 file_type`;
if [ $filetype = "ANALYZE-7.5" ] ; then
    nifti=no;
else 
    nifti=yes;
fi

orient=yes;
if [ $nifti = yes ] ; then
    if [ `$FSLDIR/bin/fslval $1 sform_code` -gt 0 ] ; then
	labs=`$FSLDIR/bin/fslhd $1 | grep sform_.orient | sed 's/[^A-Z]//g'`;
    elif [ `$FSLDIR/bin/fslval $1 qform_code` -gt 0 ] ; then
	labs=`$FSLDIR/bin/fslhd $1 | grep qform_.orient | sed 's/[^A-Z]//g'`;
    else
	labs="RL PA IS";  # default - but not safe
	orient=no;
    fi
fi

comm="$FSLDIR/bin/fslswapdim $1"
for fn in $2 $3 $4 ; do
    cc=`echo Q$fn | sed 's/[RLAPIS]//g'`;
    if [ $cc = "Q" ] ; then
	if [ $nifti = no ] ; then
	    echo "Cannot use RLAPSI notation for non-nifti files"
	    exit 2
	fi
	if [ $orient = no ] ; then
	    echo "Cannot use RLAPSI notation for nifti files without either sform or qform set"
	    exit 2
	fi
	cc=`get_axis $fn $labs`;
    else 
	cc=$fn;
    fi
    comm="$comm $cc";
done

comm="$comm $5"

echo $comm

