#!/bin/sh

#   fslvbm_3_proc - FSLVBM - the rest of it!!
# 
#   Gwenaelle Douaud & Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .fslvbmlog

D=${FSLDIR}/bin/DR
mkdir -p stats
cd FAi

echo "Now running the preprocessing steps and the pre-analyses"

/bin/rm -f fslvbm3a
for g in `$FSLDIR/bin/remove_ext *FAi.hdr` ; do
  echo $g
  echo -n "${FSLDIR}/bin/tbss_reg ${g}_GM template_GM -a ; " >> fslvbm3a
  echo -n "${D}/jacobian template_GM.hdr ${g}_JAC_aff.hdr ${g}_GM_to_template_GM_affine.dof ; " >> fslvbm3a
  echo -n "${D}/jacobian template_GM.hdr ${g}_JAC_nl.hdr  ${g}_GM_to_template_GM_nonlinear.dof ; " >> fslvbm3a
  echo "$FSLDIR/bin/fslmaths ${g}_GM_to_template_GM -mul ${g}_JAC_nl -div ${g}_JAC_aff ${g}_GM_to_template_GM_mod -odt float " >> fslvbm3a
done
chmod a+x fslvbm3a
fslvbm3a_id=`${FSLDIR}/bin/fsl_sub -T 200 -N fslvbm3a -t ./fslvbm3a`
echo Doing registrations: ID=$fslvbm3a_id
  
cd ../stats

cat <<stage_preproc2 > fslvbm3b
#!/bin/sh

\$FSLDIR/bin/imcp ../FAi/template_GM template_GM
\$FSLDIR/bin/imcp ../FAi/T MNI152_grey

\$FSLDIR/bin/fslmerge -t GM_merg \`\${FSLDIR}/bin/imglob -oneperimage ../FAi/*_GM_to_template_GM.*\`
\$FSLDIR/bin/fslmerge -t GM_mod_merg \`\${FSLDIR}/bin/imglob -oneperimage ../FAi/*_GM_to_template_GM_mod.*\`

### Creation of the mask for the statistical analyses 

\$FSLDIR/bin/fslmaths GM_merg -Tmax max_GM
\$FSLDIR/bin/fslmaths GM_merg -Tmin -bin -mul max_GM -thr 100 -bin max_GM_mask -odt char

### Convolution with different smoothing kernels (sigma not FWHM) and run of randomise with only one permutation (no correction for multiple comparisons)

/bin/cp ../design.* .

for i in GM_mod_merg ; do

  for j in 2.5 3 3.5 4 ; do
    
    \$FSLDIR/bin/fslmaths \$i -s \$j \${i}_s\${j} 
    \$FSLDIR/bin/randomise -i \${i}_s\${j} -o \${i}_s\${j} -m max_GM_mask -d design.mat -t design.con -n 1 -V
  
  done

done

/bin/rm *_vox_* *_max_*
  
stage_preproc2

chmod a+x fslvbm3b

fslvbm3b_id=`${FSLDIR}/bin/fsl_sub -T 15 -N fslvbm3b -j $fslvbm3a_id ./fslvbm3b`

echo Doing subject concatenation and initial randomise: ID=$fslvbm3b_id

echo "Now run randomise with 5000 permutations on the best smoothed 4D GM with the appropriate -c threshold for the correction for multiple comparisons"

