#!/bin/sh
Usage() {
echo "./clare.script <structural> <fieldmap>"
echo ""
echo "Used for postprocessing data of real scan images in order to generate input files for the simulator. "
echo "<structural> is a structural image in the nifti format. Just put the main name and not the extension."
echo "<fieldmap> are 2 complex volumes (in the one file) acquired for two difernet TEs.Also in nifti format. Do not put extension."
echo "<t1t2> is 1. a series name - need three series in fid format and run the script on 'phal' OR 2. def , in which case it will take brain-web values OR 3. mj, in which case it will take mj's values for T1 and T2. "
echo ""
echo "OUTPUT is a directory, siminput, which contains files: brain, MRpar, b0. "
echo ""
exit
}
[ "$1" = "" ] && Usage

struct=$1
fmap=$2


echo "brain generation..."

#run bet on $struct in order to remove the skull and stuff.
#bet ${struct} ${struct}_brain -f 0.5 -g 0 

#running fast in order to obtain all of the segmented partial volumes. For this case we only use one chanel input T1-weighted image. The output of this is $struct_brain_seg_0-2 for thre different tissue types,$struct_seg is all of them in one image, $struct_bias is the estimates biased field (1/bias). In order to calculate the restore image you just need to multiply this field with the $struct.

#fast -t1 -c 3 -os -ob -od ${struct}_brain ${struct}_brain
#avwmerge -t brain ${struct}_brain_seg_1  ${struct}_brain_seg_2 ${struct}_brain_seg_0 

#---------------------------------------------------
#fieldmap

echo "b0 generation ... "

TEdiff=0.0025
gamma=2.675e+8
avwcomplex -realabs $fmap ${fmap}abs 0 1
avwcomplex -realphase ${fmap} ${fmap}phase1 0 0
avwcomplex -realphase ${fmap} ${fmap}phase2 1 1

avwmaths_32R ${fmap}phase1 -sub ${fmap}phase2 ${fmap}phasediff

avwcomplex -complexpolar ${fmap}abs ${fmap}phasediff ${fmap}complex 0 0 
avwcomplex -realphase ${fmap}complex ${fmap}phase 0 0

prelude -a ${fmap}abs -p ${fmap}phase -o ${fmap}uphase -v
avwmaths_32R ${fmap}uphase -mul 1000 -div 2.5  b0_radps
avwmaths_32R b0_radps -div ${gamma} b0_tesla

#register b0 (which is now in tesla) to the structural image
bet ${fmap}abs ${fmap}abs_brain -f 0.5 -g 0

flirt -in ${fmap}abs_brain -ref ${struct} -omat regmatrix.mat  -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 7

flirt -in b0_tesla -ref ${struct} -out b0 -applyxfm -init regmatrix.mat -interp trilinear

avwmaths b0 -mul -1 b0z_dz
#---------------------------------------------------
#put only needed files into a directory

