#!/bin/sh
Usage() {
    echo "./generate_pulse <brain> <subjdir> "
    echo ""
    echo "Copy this file from its location to your working dir"
    echo "use ti as gui"
exit
}
[ "$1" = "" ] && Usage

brain=$1
subjdir=$2

seq=epi         #      def=epi
TE=0.030       #(s),  def=0.03        
TR=3    #(s),  def=3  
TRslc=0.12  #(s),  def=0.12 =  TR/numslc for epi
                 #               =  TRline for ge 

readdir=x
Nread=64
phasedir=y            #      def=64  -- Nread
Nphase=64            #      def=64  -- Nphase
dread=0.004         #(m),  def=0.004 = FOV/Nread
dphase=0.004         #(m),  def=0.004 = FOV/Nphase

slcthk=0.002     #(m),  def=0.006 

numvol=2     #      def=1                                  
numslc=2     #      def=1                             
  
zstart=0.03     #(m),  def=0
slcdir=z+
gap=0            #(m),  def=0  
maxG=0.055       #(T/m),def=0.055
riseT=0.00022    #(s),  def=0.00022
BW=100000        #(Hz), def=100000=100KHz                               

#POSSUMDIR=~ivana/fsldev/${FSLMACHTYPE}/bin

${POSSUMDIR}/pulse -i $brain -o pulse --te=${TE} --tr=${TR} --trslc=${TRslc} --nx=${Nread} --ny=${Nphase} --dx=${dread} --dy=${dphase} --maxG=${maxG} --riset=${riseT} --bw=${BW} --numvol=${numvol} --numslc=${numslc} --slcthk=${slcthk} --zstart=${zstart} --seq=${seq} --slcdir=${slcdir} --readdir=${readdir} --phasedir=${phasedir} -v

mv pulse* $subjdir/
