#!/bin/sh

# Copyright (C) 2007 University of Oxford
# Authors: Ivana Drobnjak, Mark Jenkinson

# shcopyright


Usage() {
    echo ""
    echo "Usage: possumX <subject directory> [options]"
    echo ""
    echo "Subject directory needs to contain:"
    echo "1.  brain"
    echo "2.  MRpar" 
    echo "3.  motion "
    echo "4.  slcprof"
    echo "5.  pulse,pulse.info"
    echo "optional"
    echo "6.  T2"
    echo "7.  T2timecourse"
    echo "8.  b0inh"
    echo "9.  b0extra"
    echo "10. b0timecourse"
    echo ""
    echo "In case there is an SGE enviroment:"
    echo "-n (number of processors, default 1)"   
    echo "-t (estimated running time per processor (minutes), default 2000)"
    exit
}

make_absolute(){
    dir=$1;
    if [ -d ${dir} ]; then
	OLDWD=`pwd`
	cd ${dir}
	dir_all=`pwd`
	cd $OLDWD
    else
	dir_all=${dir}
    fi
    echo ${dir_all}
}

run(){
 echo "$1" >> $2/possum.com
 echo "$1" >> $2/possum.log
 date >> $2/possum.log
 $1 >> $2/possum.log 2>&1
 date >> $2/possum.log
}

nargs=$#
if [ $nargs -eq 0 ] ; then
  Usage
fi

subjdir=`make_absolute $1`
subjdir=`echo $subjdir | sed 's/\/$/$/g'`
echo subjectdir is $subjdir

nproc=1
ntime=2000
while [ ! -z "$2" ]
do
  case "$2" in
      -n) nproc=$3;shift;;
      -t) ntime=$3;shift;;
      *) break;;
  esac
  shift
done

#check that all required files exist

if [ ! -d $subjdir ]; then
	echo "subject directory $1 not found"
fi

if [ ! -e ${subjdir}/motion ]; then
	echo "${subjdir}/motion not found"
fi

if [ ! -e ${subjdir}/MRpar ]; then
	echo "${subjdir}/MRpar not found"
fi

if [ ! -e ${subjdir}/slcprof ]; then
	echo "${subjdir}/slcprof not found"
fi

if [ ! -e ${subjdir}/pulse ]; then
	echo "${subjdir}/pulse not found"
fi

if [ ! -e ${subjdir}/pulse.info ]; then
	echo "${subjdir}/pulse.info not found"
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/brain` -eq 0 ]; then
  if [  `${FSLDIR}/bin/imtest ${subjdir}/object` -eq 0 ]; then
	echo "could not find ${subjdir}/brain or ${subjdir}/object"
	exit 1
  else
        command="-i ${subjdir}/object"
  fi
else
  command="-i ${subjdir}/brain"
fi

command="$command -x ${subjdir}/MRpar -f ${subjdir}/slcprof -p ${subjdir}/pulse -m ${subjdir}/motion "

if [  -e ${subjdir}/b0timecourse ]; then
	command="$command --b0time=${subjdir}/b0timecourse -l 4"
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/RFtrans` -eq 1 ]; then
	command="$command -s ${subjdir}/RFtrans"
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/RFrec` -eq 1 ]; then
	command="$command -r ${subjdir}/RFrec"
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/T2` -eq 1 ]; then
	command="$command -a ${subjdir}/T2 -t ${subjdir}/T2timecourse"
        if [ ! -e ${subjdir}/T2timecourse ]; then
	   echo "${subjdir}/T2timecourse not found"
        fi
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/T2_4D` -eq 1 ]; then
	command="$command -q ${subjdir}/T2_4D -u ${subjdir}/T2_4Dtimecourse"
        if [ ! -e ${subjdir}/T2_4Dtimecourse ]; then
	   echo "${subjdir}/T2_4Dtimecourse not found"
        fi
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/b0z_dz` -eq 1 ]; then
	command="$command -b ${subjdir}/b0"
fi

if [ `${FSLDIR}/bin/imtest ${subjdir}/b0extra` -eq 1 ]; then
	command="$command --b0extra=${subjdir}/b0extra"
fi

if [ -e ${subjdir}/nospeedup ]; then
        command="$command --nospeedup"
fi

if [ -e ${subjdir}/kcoord.on ]; then
        command="$command -k"
fi

if [ ! -e ${subjdir}/noise ]; then
        echo "sigma" 0 > ${subjdir}/noise
fi
    
echo Making possum directory structure
mkdir -p ${subjdir}/diff_proc
mkdir -p ${subjdir}/logs
mkdir -p ${subjdir}/logs/pid_${$}
mailto=`whoami`@fmrib.ox.ac.uk
    
echo Processing stage 
command="$command --nproc=${nproc}"
[ -f ${subjdir}/possum.com ] && rm ${subjdir}/possum.com
for ((procnum=0; procnum < $nproc; procnum++)) ; do
    echo "${FSLDIR}/bin/possum $command --procid=${procnum}  -o ${subjdir}/diff_proc/signal_proc_${procnum}" >> ${subjdir}/possum.com
done

possumid=`${FSLDIR}/bin/fsl_sub -T $ntime -l ${subjdir}/logs -M $mailto -N possumx -t ${subjdir}/possum.com` 

echo Post processing stage
mergeid=`${FSLDIR}/bin/fsl_sub -T 10 -j $possumid -F -l ${subjdir}/logs ${FSLDIR}/bin/possumX_postproc.sh $subjdir $nproc`

echo Done
exit 0
