#!/bin/sh

if [ $# -ge 1 ] ; then
  PROJECTS="$@";
else
# only build really necessary subprojects
  PROJECTS="utils miscmaths \
newimage libhfunc libss libvis meshclass misc_tcl bint \
afni avwutils bet bet2 cluster fast fdt feat5 film filmbabe flame flirt \
fslpres fugue mcflirt melodic2 misc_c miscvis mm \
randomise siena slicetimer susan tbss \
dropouts ifit load_varian taldaemon misc_scripts fast4 shapeModel first possum sgeutils";
fi

# don't write to a file, but print to the console
echo "Building projects..."
./config/common/buildproj $PROJECTS

