#!/bin/sh

#   runfsl - wrapper script for running jobs, via batch system if present
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2006 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 3.3 (c) 2006, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: runfsl [-n] [-b] [-t <job-duration>] <command>"
    echo ""
    echo "-n                 : don't print the command's standard output and error"
    echo "-b                 : background (submit job and exit); otherwise runfsl waits to exit until <command> has finished"
    echo "-t <job-duration>  : expected duration of job, in minutes, for use by batch scheduler (default: between 120 and 1440)"
    echo ""
    exit 1
}

if [ _$1 = _ ] ; then
    Usage
fi

logout=1
if [ $1 = -n ] ; then
    logout=0
    shift
fi

wait=1
if [ $1 = -b ] ; then
    wait=0
    shift
fi

# change the following to tune your batch submission according to the expected job duration
sgeq=long.q
if [ $1 = -t ] ; then
    duration=$2
    if [ $duration -lt 120 ] ; then
	sgeq=short.q
    fi
    if [ $duration -gt 1440 ] ; then
	sgeq=verylong.q
    fi
    shift 2
fi

# change the following to test for whether this is run on a batch submission computer and to the setup the batch submission
# TMPDIR is the place where batch logfiles get created
if [ _$SGE_ROOT != _ ] ; then
    TMPDIR=${HOME}/.fsltmp
    if [ ! -d $TMPDIR ] ; then
	mkdir $TMPDIR
    fi
    jobname=`basename $1`
    sge_id=`qsub -V -cwd -shell n -b y -m n -N $jobname -q $sgeq $@ | awk '{print $3}'`
    #sge_id=`qsub -V -cwd -shell n -b y -m n -N $jobname -q $sgeq -o $TMPDIR -e $TMPDIR $@ | awk '{print $3}'`
    echo "SGE ID = $sge_id"
else    
    if [ $wait = 1 ] ; then
	$@
    else
	$@ &
    fi
fi

# change the following to keep looping until the submitted job has finished
if [ $wait = 1 ] && [ _$sge_id != _ ] ; then
    while [ _`qstat | awk '{print $1}' | grep $sge_id` != _ ] ; do
	sleep 5
    done
    if [ $logout = 1 ] ; then
	#cat ${TMPDIR}/${jobname}.o$sge_id
	#cat ${TMPDIR}/${jobname}.o$sge_id
	cat ${jobname}.e$sge_id
	cat ${jobname}.e$sge_id
    fi
fi

