# $Id: Makefile,v 1.5 2008/08/10 09:21:34 brian Exp $
include ${FSLCONFDIR}/default.mk

PROJNAME = shapeModel

SHAPEOBJS=shapeModel.o
 

all: shapeModel.a 

shapeModel.a: ${SHAPEOBJS}
	${AR} -r libshapeModel.a ${SHAPEOBJS}




