void image_oned_fft_r(float*,int,int,int);
void image_oned_ifft_r(float*,int,int,int);
void image_oned_fft_c(float*,int,int,int);
void image_oned_ifft_c(float*,int,int,int);
void image_oned_fft_s(float *name,int ppl,int lpi,int ipv);
void image_oned_ifft_s(float *name,int ppl,int lpi,int ipv);
void four1_scaled(float*,int,int);
void xtrt(register float *,register int,register float *,register int,register int,register int,register int,register int);
void centralise(register float* data,register int pts);
void image_oned_fft_sp(float *name,int ppl,int lpi,int ipv,float p);
