int read_petable(char* petable_filename,int** petable);
int tabc(float *data,int ppl,int lpi,int ipv,int* petable);
int msreorder(float *data,int ppl,int lpi,int ipv,int vols);
int epireorder(float *data,int ppl,int lpi,int ipv,int nseg,int vols);
int llepireorder(float *data,int ppl,int lpi,int ipv,int vols);
void baseline(float *data,int ppl,int lpi,int ipv,int vols);
void lv_modulus(float *data,long volsize);
void phase(float *data,long volsize);
void real(float *data,long volsize);
void imag(float *data,long volsize);
void CalcMaxMin(float *data,long volsize,float *max,float *min);
void copyrow(float *in,float *out,int ppl,int rev);
int rotate(float *data,int ppl,int lpi,int nim,int rot);
void median_baseline(float *data,int ppl,int lpi,int ipv,int vols);
void median_baseline_3d(float *data,int ppl,int lpi,int ipv,int vols,int hks);
int zerofill(float *data,int dppl,int dlpi,int ppl,int lpi,int ipv,int edgefill);
int zerofill_3d(float *data,int dppl,int dlpi,int dipv,int ppl,int lpi,int ipv,int edgefill);
void CalcMedian(float *data,long volsize,float *max,float *min);
void cpslice(float *in,float *out,long pts);
int reflect_lines(float *data,int ppl,int lpi,int ipv);
int reflect_points(float *data,int ppl,int lpi,int ipv);
float median(double index,float *in,int inlen);
double magnitude(double x,double y);
int find_centre_kspace(float *data,int ppl,int lpi,int ipv);
void find_centre_kspace_array(float *data,int ppl,int lpi,int ipv,int* array);
int looppss_reorder(float *data,int ppl,int lpi,int ipv,int blocks,int index);
void downsample(float* cplx_data, int ppl, int lpi, int ipv, int downsamp);
void reverse_slices(float *data,int ppl,int lpi,int ipv);
int epikreorder(float *data,int ppl,int lpi,int ipv,int nseg,int kh,int vols);
float median_greaterthan_zero(double index,float *in,int inlen);
void apply_ppe(float *data,int ppl,int lpi,int ipv,float angle);
void apply_ppe2(float *data,int ppl,int lpi,int ipv,float angle);
void kpsf_filter(float *data,int ppl,int lpi,int ipv,float a,float b);
void custom_filter(float *data,int ppl,int lpi,int ipv,char* infile1);
void cencor(float *data, int ppl,int lpi,int ipv);
