#!/bin/sh

cd ${FSLDIR}/etc/standard

${FSLDIR}/bin/avwmaths_16SI avg152T1_gray -sub avg152T1_white -bin grot1
${FSLDIR}/bin/avwmaths_16SI avg152T1_gray -sub avg152T1_csf -bin grot2
${FSLDIR}/bin/avwmaths_8UI grot1 -mul grot2 grotg

${FSLDIR}/bin/avwmaths_16SI avg152T1_white -add 1 -sub avg152T1_gray -bin grot1
${FSLDIR}/bin/avwmaths_16SI avg152T1_white -sub avg152T1_csf -bin grot2
${FSLDIR}/bin/avwmaths_8UI grot1 -mul grot2 -mul 2 grotw

${FSLDIR}/bin/avwmaths_16SI avg152T1_csf -add 1 -sub avg152T1_gray -bin grot1
${FSLDIR}/bin/avwmaths_16SI avg152T1_csf -add 1 -sub avg152T1_white -bin grot2
${FSLDIR}/bin/avwmaths_8UI grot1 -mul grot2 -mul 3 grotc

${FSLDIR}/bin/avwmaths_8UI grotg -add grotw -add grotc -mul avg152T1_brain_mask avg152T1_seg

/bin/rm grot*
