#!/bin/sh

if [ _$1 = _ ] ; then
    echo "Usage: tbss_non_FA <alternative image rootname>"
    echo "e.g.: tbss_non_FA L2"
    exit 1
else
    ALTIM=$1
fi

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .tbsslog

echo "upsampling alternative images into standard space"
cd FAi
for f in *FAi.hdr ; do
    f=`$FSLDIR/bin/remove_ext $f`
    echo $f
    ${FSLDIR}/bin/applywarp -i ../${ALTIM}/FAi/$f -o ${f}_to_target_nonlinear_hr_$ALTIM -r target -w ${f}_to_target_nonlinear --rel
done

echo "merging all upsampled $ALTIM images into single 4D image"
${FSLDIR}/bin/avwmerge -t ../stats/all_$ALTIM `$FSLDIR/bin/imglob -oneperimage *_nonlinear_hr_${ALTIM}.*`
cd ../stats
$FSLDIR/bin/avwcpgeom MNI152 all_$ALTIM -d

echo "projecting all_$ALTIM onto mean FA skeleton"
thresh=`cat thresh.txt`
${FSLDIR}/bin/tbss_skeleton -i mean_FA -p $thresh mean_FA_skeleton_mask_dst ${FSLDIR}/etc/standard/lower-cingulum all_FA all_${ALTIM}_skeletonised -a all_$ALTIM

echo "now run stats - for example:"
echo "randomise -i all_${ALTIM}_skeletonised -o tbss_$ALTIM -m mean_FA_skeleton_mask -d design.mat -t design.con -n 5000 -c 3 -V"
echo "(after generating design.mat and design.con)"

