#!/bin/sh

#   tbss_1_preproc - preprocess FA data for TBSS
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2005-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage: tbss_1_preproc [-f <intensity_scaling_factor>] <image1> <image2> ..."
    echo ""
    echo "-f <intensity_scaling_factor>   : scale intensities of all input data by <intensity_scaling_factor>"
    echo "                                  this should result in a final intensity range of 0:10000"
    echo ""
    exit 1
}

[ "$2" = "" ] && Usage

echo [`date`] [`hostname`] [`uname -a`] [`pwd`] [$0 $@] >> .tbsslog

FACTOR=10000
if [ $1 = -f ] ; then
    FACTOR=$2
    shift 2
fi
echo Using multiplicative factor of $FACTOR

export FSLOUTPUTTYPE=ANALYZE

mkdir -p FAi
mkdir -p origdata

for f in `$FSLDIR/bin/imglob -oneperimage $@` ; do

    f=`$FSLDIR/bin/remove_ext $f`
    echo processing $f

    # scale intensities then erode a little
    $FSLDIR/bin/fslmaths $f -mul $FACTOR -ero FAi/${f}_FAi -odt short

    $FSLDIR/bin/fslhd -x $f | sed "s/sform_code .*/sform_code = \'0\'/g" | sed "s/qform_code .*/qform_code = \'0\'/g" > grot.xml
    $FSLDIR/bin/fslcreatehd grot.xml FAi/${f}_FAi.hdr
    /bin/rm grot.xml

    # delete end slices
    X=`${FSLDIR}/bin/fslval FAi/${f}_FAi dim1` ; X=`echo "$X 2 - p" | dc -`
    Y=`${FSLDIR}/bin/fslval FAi/${f}_FAi dim2` ; Y=`echo "$Y 2 - p" | dc -`
    Z=`${FSLDIR}/bin/fslval FAi/${f}_FAi dim3` ; Z=`echo "$Z 2 - p" | dc -`
    $FSLDIR/bin/fslroi FAi/${f}_FAi FAi/${f}_FAi 1 $X 1 $Y 1 $Z 

    $FSLDIR/bin/immv $f origdata
	
done

echo "Now running \"slicesdir\" to generate report of all converted images"
cd FAi
$FSLDIR/bin/slicesdir *.hdr > grot 2>&1
cat grot | tail -n 2
/bin/rm grot

