#!/bin/sh
# postinst script for FSL
# This script is used to regenerate the tclIndex file after placing a link to
# fslio.tcl in the main tcl path of FSL.

set -e

case "$1" in
	configure)
		( cd /usr/share/fsl/5.0/tcl && echo 'auto_mkindex . *.tcl' | tclsh )
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	#nothing
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0


