debian/tmp/bin/* usr/lib/fsl
debian/tmp/{tcl,etc} usr/share/fsl
debian/tmp/etc/fslconf/feat.tcl etc/fsl
debian/tmp/fsl.xpm usr/share/pixmaps

etc usr/share/fsl
lib/*.so usr/lib/fsl
doc/images usr/share/fsl/doc
extras/irtk/* usr/share/bin/DR

debian/fsl.sh etc/fsl
debian/desktop/*.desktop usr/share/applications
debian/fsl_gui_app_wrapper usr/lib/fsl

debian/tmp/lintian/* usr/share/lintian/overrides
