#! /bin/sh -e

# Copyright (C) 2007 by
# Michael Hanke        michael.hanke@gmail.com
#
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


if [ "${0##*/}" = "fsl_gui_app_wrapper" ]; then
	echo 'fsl_gui_app_wrapper: This script should not be run like this, see fsl(1) for details' 1>&2
	exit 1
fi

if [ -z "${FSLDIR}" ]; then
	. /etc/fsl/fsl.sh
fi

exec /usr/lib/fsl/${0##*/} $@

