#!/bin/sh

Usage() {
	echo "Usage: afni2avw <input_fileroot>"
	exit
}

[ "$1" = "" ] && Usage

which 3dinfo >/dev/null 2>&1
if [ $? -ne 0 ] ; then
 echo "ERROR: This program uses AFNI's 3dinfo command, but 3dinfo was not found in your PATH."
 exit 1
fi

x=`3dinfo $1 | grep R-to-L | sed "s/\[//g" | awk '{print $11}'`
y=`3dinfo $1 | grep A-to-P | sed "s/\[//g" | awk '{print $11}'`
z=`3dinfo $1 | grep I-to-S | sed "s/\[//g" | awk '{print $11}'`

xv=`3dinfo $1 | grep R-to-L | awk '{print $9}'`
yv=`3dinfo $1 | grep A-to-P | awk '{print $9}'`
zv=`3dinfo $1 | grep I-to-S | awk '{print $9}'`

echo "x=$x y=$y z=$z xv=$xv yv=$yv zv=$zv"

$FSLDIR/bin/avwcreatehd $x $y $z 1 $xv $yv $zv 3 0 0 0 4 $1

/bin/cp -f $1.BRIK $1.img

