#!/bin/sh

Usage() {
	echo "Usage: avw2afni <input_fileroot>"
	exit 1
}

[ "$1" = "" ] && Usage

which to3d >/dev/null 2>&1
if [ $? -ne 0 ] ; then
 echo "ERROR: This program uses AFNI's to3d command, but to3d was not found in your PATH."
 exit 1
fi
     
/bin/rm -f $1+orig.BRIK $1+orig.HEAD

to3d -prefix $1 -session . -orient RPS $1.hdr

