include ${FSLCONFDIR}/default.mk

PROJNAME = misc_scripts

SCRIPTS = regscript remove_vols replacevols replace_and_average_fmrib linkbedpost ocmr_preproc correct_and_average eddy_correct fslmachtype

all:
