#!/bin/sh

#   run_first_all - wrapper script for "first", the main FIRST fitting
#
#   Brian Patenaude/Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 4.0 (c) 2007, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage:   run_first_all <input_image> <boundary_threshold> <output>"
    echo ""
    echo "e.g.:  run_first_all im1 4 output_name "
    echo ""
    exit 1
}

[ "$3" = "" ] && Usage
[ `${FSLDIR}/bin/imtest $1` = 0 ] && Usage
A=`${FSLDIR}/bin/remove_ext $1`
Af=`echo $A | awk -F / '{print $NF}'`

echo ${FSLDIR}/bin/first_flirt $A ${Af}_to_std

FLIRTID=`${FSLDIR}/bin/fsl_sub -T 15 ${FSLDIR}/bin/first_flirt $A ${Af}_to_std`
COM=${3}.com
/bin/rm -f ${COM}*

imscorr=""
imsfirst=""

for s in L_Accu L_Amyg L_Caud L_Hipp L_Late L_Pall L_Puta L_Thal R_Accu R_Amyg R_Caud R_Hipp R_Late R_Pall R_Puta R_Thal BrStem; do
   
    intref=0;
    case "${s:2:4}" in 
	Accu)
	    nmodes=50
	    ;;
	Amyg)
	    nmodes=50;
	    intref=1;
	    ;;
	Caud)
	    nmodes=30;
	    intref=1;
	    ;;
	Hipp)
	    nmodes=30;
	    intref=1;
	    ;;
	Late)
	    nmodes=40;
	    intref=1;
	    ;;
	Pall)
	    nmodes=40;
	    ;;
	Puta)
	    nmodes=40;
	    ;;
	Thal)
	    nmodes=40;
	    ;;
	Stem)
	    nmodes=40;
	    ;;
	*)
	    echo "Structure unknown"
	    exit 1

    esac
    #run_first , choose between normal and intref
    if [ $intref = 0 ] ; then 
	echo -n "${FSLDIR}/bin/run_first -i $A -t ${Af}_to_std.mat -n $nmodes -o ${3}-${s}_first -m ${FSLDIR}/data/first/models_317_bin/${s}_bin.bmv" >> $COM
    else
	echo -n "${FSLDIR}/bin/run_first -i $A -t ${Af}_to_std.mat -n $nmodes -o ${3}-${s}_first -m ${FSLDIR}/data/first/models_317_bin/intref_thal/${s}_bin.bmv -intref ${FSLDIR}/data/first/models_317_bin/${s:0:1}_Thal_bin.bmv" >> $COM

    fi
      
    ##boundary correction 
    echo "; ${FSLDIR}/bin/first_utils --singleBoundaryCorr -i ${3}-${s}_first -r $A -p $2 -o ${3}-${s}_corr" >> $COM
   
    imsfirst="${imsfirst} ${3}-${s}_first"
    imscorr="${imscorr} ${3}-${s}_corr"

done

FIRSTID=`${FSLDIR}/bin/fsl_sub -T 60 -N first -j $FLIRTID -t $COM`

threshnop=`echo ${2} | sed 's/\.//g'`

echo "${FSLDIR}/bin/fslmerge -t ${3}_all_th${threshnop}_first ${imscorr} ; ${FSLDIR}/bin/fslmaths ${3}_all_th${threshnop}_first -Tmean -mul 16 ${3}_all_th${threshnop}_first -odt int ; ${FSLDIR}/bin/fslmerge -t ${3}_all_th${threshnop}_first ${3}_all_th${threshnop}_first  ${imsfirst}" > ${COM}2

MERGEID=`fsl_sub -T 15 -N first_post -j $FIRSTID -t ${COM}2`

echo "${FSLDIR}/bin/imrm ${3}-*_corr* ${3}-*_first*" >${COM}3

fsl_sub -T 5 -N clean_up -j $MERGEID -t ${COM}3 

