#!/bin/sh

#   run_flirt - wrapper script for "first", the main FIRST fitting
#
#   Brian Patenaude, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 3.3 (c) 2006, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/1112.

Usage() {
    echo ""
    echo "Usage:   run_first <input_image> <input_to_mni.mat> <N-modes> <output_basename> <model_name> [more model names]"
    echo ""
    echo "e.g.:  run_first im1 im1_to_mni.mat 60 output_name ${FSLDIR}/etc/standard/first_models_317_bin/L_Hipp_bin.bmv"
    echo ""
    exit 1
}

[ "$5" = "" ] && Usage
[ `${FSLDIR}/bin/imtest $1` = 0 ] && Usage

file=`${FSLDIR}/bin/remove_ext $1`
shift 
trmat=$1
shift
g=$1
shift 
outname=`${FSLDIR}/bin/remove_ext $1`
shift


mean=-777 ;
# disabled
#use robust statistics
ub=`${FSLDIR}/bin/avwstats $file -r | awk '{ print $2 }'`
lb=`${FSLDIR}/bin/avwstats $file -r | awk '{ print $1 }'`

count=0;

for model in $@; do
    echo ${model}
    if [ -f ${model} ]; then
	if [ -f ${trmat} ]; then

	#apply model
	  
	${FSLDIR}/bin/first --baam -i ${file} -l ${trmat}  -m ${model} -k  ${outname}_first -s 8 -g ${g}  -y ${lb} -z ${ub} -a ${mean};
	
	else
	    echo "linear transformation matrix file not found"
	fi
    else
	echo "model file not found"
    fi
done;

